config/routes.rb
Rails.application.routes.draw do
 resources :items 
  devise_for :users
  
  resources :charges
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :carts 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :cart
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end
  
  def create
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController


  def index
    @items = Item.all
    
  end

  def show
    @item_searched = Item.find(params[:id])
  
  end
 
  def update
  end

  def destroy
  end

  def new
  end

  def edit
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Amount: $5.00</span>
      </label>
    </article>
  
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="A month's subscription"
            data-amount="500"
            data-locale="auto"></script>
  <% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<center>
<div class="jumbotron">
    <h1 class="display-4">Petit Chat</h1> <br> 
    <p class="lead">Toutes les occasions sont bonnes pour offrir un cadeau à un amoureux des chats</p> <br>
    <hr class="my-4"> <br> <br>
    <p class="lead">Choisis une photo </p> <br>

    <p class="lead">
      <a class="btn btn-primary btn-lg" href="<%= items_path %>" role="button">Voir nos produits</a>
    </p>
  </div></center>

  <div class="row text-center">
<% @items.each do |item| %>
<div class="col-lg-3 col-md-6 mb-4">
  <div class="card shadow bg-white rounded ml-1">
    <img class="card-img-top" src="<%= item.image_url %>" alt="">
    <div class="card-body">
      <h4 class="card-title"><%= item.title %></h4>
      <p><%= item.price %>€</p>
    </div>
    <div class="card-footer">
      <%= link_to "Acheter", item_path(item.id), class: "btn btn-primary" %>
    </div>
  </div>
</div>
<% end %>

</div>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="ressource.css" />
        <script src="https://kit.fontawesome.com/f2f9fc2fd7.js" crossorigin="anonymous"></script>
        <script src='https://kit.fontawesome.com/a076d05399.js'></script>
       <title><%= @item_searched.title%></title>
        
</head>

<body>
  <div class="container">
    <div class = "row border">

 
      <div class="col-md-8 p-0">
        <img style="width:55%; height:500px; display: block; border-radius:5px" src= <%=  @item_searched.image_url %> alt="Event image">
      </div>


      <div class="col-md-4 p-5">
        <div class="row">
            <p>Un petit chat à adopter en photo ? </p
            <br>
        </div>
        <div class="row">
          <h3> <%= @item_searched.title%></h3>
        </div>
        <div class="row">
         
          
        </div>

        <div class="row align-self-end">
              <h2 class="mt-5">A propos de cette photo</h2>
            <p> <%= @item_searched.description %> </p>
             
              <p> <h4>PRIX : <%= @item_searched.price %> € </h4> </p>
              <a href="#" class="btn btn-primary" >Ajouter dans le panier </a>
        </div>
        </div>
      </div>
  </div>
  
  <div class="container">
    <div class = "row">
        <div class="row col-md-8 p-0">
        
        </div>
        
    </div>
  </div>
      <div class="col-md-6 col-lg-7 text-center text-md-right">
        <h5 class="mt-5">Partager cette photo</h5>
        <!--Facebook-->
        <a><i class="fab fa-facebook white-text mr-4"></i></a>  
        <!--Twitter-->
        <a><i class="fab fa-twitter white-text mr-4"></i></a>
        <!--Linkedin-->
        <a><i class="fab fa-linkedin white-text mr-4"></i></a>
        <!--Instagram-->
        <a><i class="fab fa-instagram white-text mr-lg-4"></i></a>          
      </div>
  
</div>
</body>
</html>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/_footer.html.erb
<!-- <footer class="footer_area clearfix">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-12 col-lg-4">
                <div class="single_widget_area">
                    <div class="footer-logo mr-5">
                        <a href="/"><img src="./img/core-img/logo2.png" style="height:100px; width:100px;" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-8">
                <div class="single_widget_area">
                    <div class="footer_menu">
                        <nav class="navbar navbar-expand-lg justify-content-end">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent"
                                aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i
                                    class="fa fa-bars"></i></button>
                            <div class="collapse navbar-collapse" id="footerNavContent">
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item">
                                        <a class="nav-link" href="checkout.html">Contact</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PicturesCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/product/">
    <script src="https://kit.fontawesome.com/f2f9fc2fd7.js" crossorigin="anonymous"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/lux/bootstrap.min.css" integrity="sha384-9+PGKSqjRdkeAU7Eu4nkJU8RFaH8ace8HGXnkiKMP9I9Te0GJ4/km3L1Z8tXigpG" crossorigin="anonymous">
    
   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" >PetitChat</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= items_path %>">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" href="<%= new_user_registration_path %>">S'inscrire</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_user_session_path %> ">Se connecter</a>
      </li>
      
      <div class="topnav-right">
      <button class="btn"><i class="fa fa-shopping-basket fa-2x"></i></button>
      </div>
    </ul>
    
  </div>
</nav>
  <body>
    <%= yield %>

    </body>
  

app/views/layouts/charges.html.erb
<!DOCTYPE html>

<html> 
    <head>
    </head> 
         <body>   
            <%= yield %> 
         </body>
 </html>